name: Format YAML

on:
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch: # to trigger manually

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Format YAML files
        uses: ./
        with:
          path: .github/**/*.yml .github/**/*.yaml

      - name: Commit changes
        if: github.event_name == 'push'
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git diff --quiet || (git add -A && git commit -m 'style: format yaml files' && git push)
